### ISSUE TITLE
allow custom metrics path

### ISSUE THREAD

**Issue by noave** [Uberspace/django_aetos#10]
Looks like `/metrics` is hardcoded within aetos urls, use root path there and allow to set it when including the aetos urls.

```
from django.urls import include

urlpatterns = [
    path("/metrics", include("django_aetos.urls")),
    # ... your other patterns ...
]
```

**Comment by luto** [comment]
aetos uses `/metrics` because that's the standard path in prometheus. You can use an other path by referencing `django_aetos.views.export_metrics` directly within your `urls.py`.
